---
- hosts: web
  become: true
  tasks:
    - name: Install nginx
      yum: pkg=nginx state=installed update_cache=yes
      notify:
        - start-webserver
      tags:
        - hello-world

    - name: Copy webpages
      copy: 
        src: files/infotern 
        dest: /usr/share/nginx/html
        mode: 0644
      notify:
        - restart-webserver


   handlers:
     - name: start-webserver
       service: name=nginx state=started enabled=yes

     - name: restart-webserver
       service:
         name: nginx
         state: restarted
     
      
